### ISSUE TITLE
Fallback/Alternate Stream

### ISSUE THREAD

**Issue by davidjk1** [THEOplayer/samples-html5-sdk#26]
Hello, 
I'm using THEOplayer with live HLS streams and wondering if it's possible to have the player fall back to an alternate stream if the primary one isn't live at the moment.  However ideally the player would routinely check the status of that main stream and, once it goes live, refresh the player to play that primary stream.  Does that sound like something that's feasible making use of the player API?

**Comment by thijsl** [comment]
Hi @davidjk1 , I understand the use-case.

Have you looked into redundant streams, as per the HLS spec at https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html? Would that serve your use-case?

Kind regards,
Thijs
