### ISSUE TITLE
Prevent play event if no source is setted

### ISSUE THREAD

**Issue by franciscohanna92** [THEOplayer/samples-html5-sdk#27]
I have a player mounted on a React app.

My goal is to prevent the play event if no source is setted. Right now, if there is no source, the player allows the play button to be pressed and then it just stays in a "loading" state:

![image](https://user-images.githubusercontent.com/12707758/76538814-a8ce0980-645e-11ea-8412-5519d8863c14.png)

Is there anyway to achieve this?

**Comment by thijsl** [comment]
Hi @franciscohanna92 -- happy to help.

Allow me to understand the use-case. You'd like your viewers to not be able to click the play button, when no source is set. Correct? (If so: what's the reason why you are setting video players without a source?)

You could try to fiddle with CSS, and leverage `pointer-events: none;`. For example, you could add a class called "no-click" as below:
`.no-click {
   pointer-events: none;
}`
Then, you could use JavaScript (or React) to [toggle this class](https://www.w3schools.com/howto/howto_js_toggle_class.asp) for your player container. Add the class when no source is set, and set the class when a source is set.

Let me know if this would work for you. :)

Good luck!

**Comment by franciscohanna92** [comment]
Hi @thijsl!

Thanks for your answer. Works like a charm!

The reason why the player is present but no source is selected is because there's a select which has nothing selected by default, and then the users changes the src on demand. So, initially, the player doesn't have a src selected and thus I need to prevent the play event. Does it make sense?

Thanks again!

**Comment by thijsl** [comment]
Makes sense. And happy I could be of help! :)
