### ISSUE TITLE
Event for quality change

### ISSUE THREAD

**Issue by franciscohanna92** [THEOplayer/samples-html5-sdk#28]
I know that I can access the available qualities for a track and the active quality using the Media Track API and the `addtrack`.

What I need now is an event to listen for quality changes in the track (i.e. if the network degrades, the quality changes). I just need the `height` (720, 144, 1080, etc). Is this possible?

**Comment by franciscohanna92** [comment]
For now, I have the following workaround:

```javascript
playerObject.videoTracks.addEventListener('addtrack', ({ track }) => {
        track.addEventListener('update', (trackEnabledEvent) => {
        if(track.activeQuality) {
            console.log(track.activeQuality.height);
        }
    });
});
```

Is this correct or it's kind of _hacky_?

**Comment by TimLeenaers** [comment]
Hi Francisco 

You can use the `activequalitychanged` event for this.

Code example: 
```js
// detect video tracks being added to the player
player.videoTracks.addEventListener('addtrack', function(e0) {
    // detect quality changes of a track
    e0.track.addEventListener('activequalitychanged', function(e1) {
        console.log('activequalitychanged event detected!', e1);
    });
});
```

**Comment by franciscohanna92** [comment]
Thanks @TimLeenaers !
