### ISSUE TITLE
Reasons for "There appears to be a playback issue".

### ISSUE THREAD

**Issue by franciscohanna92** [THEOplayer/samples-html5-sdk#29]
Hi there!

I'm working on project for which I can't give too many details about what is being done on the backend, so I just want to ask if there's a reason or a list of reasons for which the following error may come up in the player:

![image](https://user-images.githubusercontent.com/12707758/78929038-0c585080-7a78-11ea-9c5e-69b81db12d8c.png)

After this error the player enters an unrecoverable state and no controls are available for it.

I will understand if the error is too broad to know the causes for it, but anything would help.

Thanks in advance.

**Comment by thijsl** [comment]
Hi @franciscohanna92 ,

This is one of our more generic errors. 

Are you struggling with a specific issue which you want to tackle, or are you mainly interested in error handling?

Kind regards,
Thijs

**Comment by franciscohanna92** [comment]
Hi @thijsl 

I'm mainly interested in handling this error. It doesn't happen a lot and it maybe related to the streaming src.

**Comment by thijsl** [comment]
Hi @franciscohanna92,

Hmmm... Do you have a reproduction page and reproduction steps? I could take a look if you give us something to work with. (It's pretty hard to troubleshoot without this.)

Some additional questions regarding your issue and stream:
1. Live or VOD? If it's the former: are you getting 403s/404s?
2. HLS or MPEG-DASH?
3. Happening on a quality switch?
4. With all assets or some assets?
5. Happening on all browsers or some browsers?
6. Can you reproduce the issue for any demo at https://www.theoplayer.com/demo-zone?

**Comment by thijsl** [comment]
Heya @franciscohanna92 -- gentle poke and redirect to the questions above. Would love to make some progress together with you!

Have a great Friday,
Thijs

**Comment by franciscohanna92** [comment]
Hi @thijsl ! 

I'm no longer working on thtat project (it finished this week), but, regarding your questions:

1. VOD
2. Not sure. I think HLS.
3. Yes
4. Can't really tell.
5. Only tested on Chrome

I know my answers are kind of vague, but I hope they help!

**Comment by thijsl** [comment]
This helps, @franciscohanna92. Thanks!
Should we close this issue, as you've stopped working on it?

(PS. What was the outcome of the project? Did you achieve what you wanted to?)

**Comment by franciscohanna92** [comment]
Yes, I think we should close it.

Project was successful and we achieved all the objectives!

**Comment by thijsl** [comment]
Sweet! :)
