### ISSUE TITLE
Show upnext bar on pause

### ISSUE THREAD

**Issue by wilhem-puljanan** [THEOplayer/samples-html5-sdk#33]
I am trying to show the upnext bar created during the pause event but it's now showing.
I am using this : this._player.upnext.bar.show()
Is it possible?

Thanks

**Comment by thijsl** [comment]
Hi @wilhem-puljanan,

Thanks for raising your first Github issue in our humble repository. We're happy to have you! 🤗

You're using the correct API. 

However, there seems to be some sort of timing issue when you subscribe to the `pause` event and trigger `player.upnext.bar.show()` upon receiving this event. I've got a solution working with a `setTimeout`. Admittedly you never want to use such logic, but it does do the trick...

```
player.addEventListener('pause', function() {
   setTimeout(function(){ player.upnext.bar.show(); }, 500);
});
```

Alternatively, you could try to manipulate the feature with custom JavaScript and CSS.

If neither solution would fit your needs, I'd encourage you to reach out to your THEOplayer account manager and refer to this Github issue, or use the chat-function in portal.theoplayer.com and refer to this Github issue.

Have a wonderful Friday,
- Thijs

**Comment by thijsl** [comment]
Hi @wilhem-puljanan,

Did the feedback above help? (Can we close this?)
